# Mosquitto Configuration
<<<<<<< HEAD
# TLS MQTT (enabled)
listener 18883
allow_anonymous true
cafile config/ca.crt
certfile config/server.crt
keyfile config/server.key
require_certificate false
tls_version tlsv1.2

persistence true
persistence_location /tmp/mosquitto/
=======
listener 11883
allow_anonymous true
persistence true
persistence_location /tmp/mosquitto/

# TLS Configuration
listener 18883
allow_anonymous true
cafile /home/saniyachavani/Documents/Precision_Pulse/dspl-precision-pulse-desktop/config/ca.crt
certfile /home/saniyachavani/Documents/Precision_Pulse/dspl-precision-pulse-desktop/config/server.crt
keyfile /home/saniyachavani/Documents/Precision_Pulse/dspl-precision-pulse-desktop/config/server.key
require_certificate false
tls_version tlsv1.2
>>>>>>> 03035868208f04d97c99349fe0cd2242f260bd0d
