# Mosquitto Configuration
# TLS MQTT (enabled)
listener 18883
allow_anonymous true
cafile config/ca.crt
certfile config/server.crt
keyfile config/server.key
require_certificate false
tls_version tlsv1.2

persistence true
persistence_location /tmp/mosquitto/
